import turtle
bob=turtle.Turtle()
gg=turtle.Turtle()
nn=turtle.Turtle()
kk=turtle.Turtle()
zz=turtle.Turtle()
hh=turtle.Turtle()
turtle.colormode(255)
bob.pensize(1)
bob.speed(0)
nn.speed(0)
kk.speed(0)
zz.speed(0)
gg.speed(0)
hh.speed(0)
turtle.bgcolor("black")

from myFunctions import*

for times in range(255):
    bob.color(255,255,255)
    bob.circle(times)
    bob.right(90)
    bob.left(97)

for times in range(256):
    bob.color(0,0,255)
    bob.forward(times)
    bob.left(240)
    gg.color(0,255,0)
    gg.forward(times)
    gg.right(245)
    nn.color(255,0,0)
    nn.forward(times)
    nn.left(250)
    kk.color(255,255,0)
    kk.forward(times)
    kk.left(255)
    zz.color(0,255,255)
    zz.forward(times)
    zz.left(260)
    hh.color(87,times,2)
    hh.forward(times)
    hh.left(260)
